import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "../components/Navbar"
import BuildArtButton from "../components/BuildArtButton"


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <ClerkProvider publishableKey="pk_test_c3BlY2lhbC1jaGlnZ2VyLTIwLmNsZXJrLmFjY291bnRzLmRldiQ">      
          <html lang="en">
            <body className={inter.className}>
                <Navbar />
                <div className="pt-24">
                  {children}
                </div>
                <BuildArtButton />
            </body>
          </html>
        </ClerkProvider>
  );
}

