import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "../components/Navbar"
import BuildArtButton from "../components/BuildArtButton"
import { SignedIn, SignedOut } from "@clerk/nextjs";
import { SignInButton } from "@clerk/nextjs";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Art App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <ClerkProvider publishableKey="pk_test_c3BlY2lhbC1jaGlnZ2VyLTIwLmNsZXJrLmFjY291bnRzLmRldiQ">      
          <html lang="en">
            <body className={inter.className}>
                <Navbar />
                <div className="pt-24">
                  {children}
                </div>
                <SignedOut>
                  <div className="fixed bottom-4 right-4 font-mono">
                    <SignInButton 
                      forceRedirectUrl="/api/userDbCheckCallback" 
                      signUpForceRedirectUrl="/api/userDbCheckCallback">
                      <button className="p-2 bg-blue-500 text-white rounded">Sign in to build art!</button>
                    </SignInButton>
                  </div>
                </SignedOut>
                <SignedIn>
                  <BuildArtButton />
                </SignedIn>
            </body>
          </html>
        </ClerkProvider>
  );
}

